import { Clock3, KeyRound, Network, RefreshCw, Save, ScrollText } from "lucide-react";
import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import { api } from "../api";
import type { AuditRecord, PanelPorts, ScheduleSettings } from "../types";

export function SettingsPage({ notify, role, onSessionExpired }: { notify: (type: "success" | "error", message: string) => void; role: "admin" | "user"; onSessionExpired: () => void }) {
  const [schedule, setSchedule] = useState<ScheduleSettings | null>(null);
  const [audit, setAudit] = useState<AuditRecord[]>([]);
  const [ports, setPorts] = useState<PanelPorts | null>(null);
  const [passwords, setPasswords] = useState({ currentPassword: "", newPassword: "", confirmPassword: "" });
  useEffect(() => { void Promise.all([api.get<ScheduleSettings>("/schedules"), api.get<AuditRecord[]>("/audit"), ...(role === "admin" ? [api.get<PanelPorts>("/admin/ports")] : [])]).then(([s, a, p]) => { setSchedule(s); setAudit(a); if (p) setPorts(p as PanelPorts); }).catch((e) => notify("error", e.message)); }, [notify, role]);
  function set<K extends keyof ScheduleSettings>(key: K, value: ScheduleSettings[K]) { setSchedule((current) => current ? { ...current, [key]: value } : current); }
  async function saveSchedule() { if (!schedule) return; try { setSchedule(await api.put<ScheduleSettings>("/schedules", schedule)); notify("success", "计划任务已保存"); } catch (e) { notify("error", e instanceof Error ? e.message : "保存失败"); } }
  async function savePorts() { if (!ports) return; try { setPorts(await api.put<PanelPorts>("/admin/ports", ports)); notify("success", "管理员端口已保存"); } catch (e) { notify("error", e instanceof Error ? e.message : "端口保存失败"); } }
  async function changePassword(event: FormEvent) { event.preventDefault(); if (passwords.newPassword !== passwords.confirmPassword) { notify("error", "两次输入的新密码不一致"); return; } try { await api.put("/auth/password", { currentPassword: passwords.currentPassword, newPassword: passwords.newPassword }); notify("success", "密码已修改，请重新登录"); onSessionExpired(); } catch (e) { notify("error", e instanceof Error ? e.message : "修改失败"); } }
  if (!schedule) return <div className="page-loading"><RefreshCw className="spin" size={20} />读取系统设置</div>;
  return <div className="settings-stack"><section className="form-section"><div className="section-heading"><h2><Clock3 size={19} />计划任务</h2><p>Asia/Shanghai</p></div><div className="schedule-grid"><div className="schedule-row"><Toggle checked={schedule.backupEnabled} onChange={(v) => set("backupEnabled", v)} /><strong>自动备份</strong><input type="time" value={schedule.backupTime} onChange={(e) => set("backupTime", e.target.value)} disabled={!schedule.backupEnabled} /></div><div className="schedule-row"><Toggle checked={schedule.updateEnabled} onChange={(v) => set("updateEnabled", v)} /><strong>自动更新</strong><input type="time" value={schedule.updateTime} onChange={(e) => set("updateTime", e.target.value)} disabled={!schedule.updateEnabled} /></div><label className="field"><span>备份保留数量</span><input type="number" min="1" max="100" value={schedule.retentionCount} onChange={(e) => set("retentionCount", Number(e.target.value))} /></label><label className="check-field"><input type="checkbox" checked={schedule.restartAfterUpdate} onChange={(e) => set("restartAfterUpdate", e.target.checked)} /><span>更新完成后恢复运行状态</span></label></div><div className="section-actions"><button className="button primary" onClick={() => void saveSchedule()}><Save size={17} />保存计划</button></div></section>
    {role === "admin" && ports && <section className="form-section"><div className="section-heading"><h2><Network size={19} />管理员端口</h2><p>Panel owned</p></div><div className="form-grid four-columns"><Field label="地面端口"><input type="number" min="1024" max="65535" value={ports.masterPort} onChange={(e) => setPorts({ ...ports, masterPort: Number(e.target.value) })} /></Field><Field label="洞穴端口"><input type="number" min="1024" max="65535" value={ports.cavesPort} onChange={(e) => setPorts({ ...ports, cavesPort: Number(e.target.value) })} /></Field><Field label="地面 Steam"><input type="number" min="1024" max="65535" value={ports.steamMasterPort} onChange={(e) => setPorts({ ...ports, steamMasterPort: Number(e.target.value) })} /></Field><Field label="洞穴 Steam"><input type="number" min="1024" max="65535" value={ports.steamCavesPort} onChange={(e) => setPorts({ ...ports, steamCavesPort: Number(e.target.value) })} /></Field></div><div className="section-actions"><button className="button primary" onClick={() => void savePorts()}><Save size={17} />保存端口</button></div></section>}
    {role === "admin" && <section className="form-section"><div className="section-heading"><h2><KeyRound size={19} />管理员密码</h2><p>Security</p></div><form className="password-form" onSubmit={changePassword}><label className="field"><span>当前密码</span><input type="password" autoComplete="current-password" value={passwords.currentPassword} onChange={(e) => setPasswords({ ...passwords, currentPassword: e.target.value })} /></label><label className="field"><span>新密码</span><input type="password" autoComplete="new-password" value={passwords.newPassword} onChange={(e) => setPasswords({ ...passwords, newPassword: e.target.value })} /></label><label className="field"><span>确认新密码</span><input type="password" autoComplete="new-password" value={passwords.confirmPassword} onChange={(e) => setPasswords({ ...passwords, confirmPassword: e.target.value })} /></label><button className="button secondary">修改密码</button></form></section>}
    <section className="panel"><div className="panel-header"><div><ScrollText size={19} /><h2>操作审计</h2></div></div><div className="table-wrap audit-table"><table><thead><tr><th>时间</th><th>操作</th><th>内容</th><th>来源</th></tr></thead><tbody>{audit.slice(0, 50).map((item) => <tr key={item.id}><td>{new Date(item.at).toLocaleString("zh-CN")}</td><td><code>{item.action}</code></td><td>{item.detail}</td><td>{item.ip}</td></tr>)}</tbody></table></div></section></div>;
}
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="field"><span>{label}</span>{children}</label>; }
function Toggle({ checked, onChange }: { checked: boolean; onChange: (value: boolean) => void }) { return <button type="button" role="switch" aria-checked={checked} className={`switch ${checked ? "on" : ""}`} onClick={() => onChange(!checked)}><i /></button>; }
